#!/bin/sh

set -e

#DEB

GROUP='stratio'
USER='stratio'
DIR_INSTALL='/opt/sds/connectors/mongodb'
DIR_CONF='/etc/sds/connectors/mongodb'
DIR_CONF='/etc/sds/connectors/mongodb'
DIR_LOG='/var/log/sds/connectors/mongodb'

ln -s /etc/sds/connectors/mongodb/conf/ /opt/sds/connectors/mongodb/conf

cp /opt/sds/connectors/mongodb/template/MongoDBConnector /etc/init.d/stratio-connector-mongodb
chmod 755 /etc/init.d/stratio-connector-mongodb
chmod 755 /opt/sds/connectors/mongodb/bin
chmod +x /opt/sds/connectors/mongodb/bin/stratio-connector-mongodb
chmod +x /etc/default/stratio-connector-mongodb
export MONGODB_CONNECTOR_LIB=/opt/sds/connectors/mongodb
export MONGODB_CONNECTOR_CONF="/etc/sds/connectors/mongodb"

case "$1" in
  configure)

  # Add stratio group if it doesn't already exists
  if ! getent group $GROUP >/dev/null 2>&1; then
    groupadd ${GROUP} 
  fi

  # Add stratio user if it doesn't already exists
  if ! getent passwd $USER >/dev/null 2>&1; then
    [ -d /opt ] || mkdir /opt
    useradd -M -d /opt/sds -g ${GROUP} -s /bin/bash ${USER}
  else
    usermod -G $GROUP $USER
  fi

  if [ ! -d "$DIR_LOG" ]; then
    mkdir $DIR_LOG
  fi

  chown -R ${USER}:${GROUP} /opt/sds /etc/sds

  chown root:root /etc/init.d/stratio-connector-mongodb
 
  chown -R ${USER}:${GROUP} $DIR_INSTALL
  ln -s $DIR_INSTALL/conf $DIR_CONF
  chown -R ${USER}:${GROUP} $DIR_CONF
  chown -R ${USER}:${GROUP} $DIR_LOG
  chmod -R 775 $DIR_INSTALL
  chmod 775 $DIR_LOG
  echo "entra"
  update-rc.d stratio-connector-mongodb defaults
  echo "sale"
  ;;
esac    


exit 0

