#!/bin/sh

set -e

#DEB

GROUP='stratio'
USER='stratio'
DIR_INSTALL='/opt/sds/connectors/mongodb'
DIR_CONF='/etc/sds/connectors/mongodb'
DIR_CONF='/etc/sds/connectors/mongodb'
DIR_LOG='/var/log/sds/connectors/mongodb'


chmod 755 /etc/init.d/connector_mongodb
chmod 755 /opt/sds/connectors/mongodb/bin
chmod +x /opt/sds/connectors/mongodb/bin/stratio-connector-mongodb
chmod +x /etc/default/mongodb_connector
export MONGODB_CONNECTOR_LIB=/opt/sds/connectors/mongodb
export MONGODB_CONNECTOR_CONF="/etc/sds/connectors/mongodb"

sed -i 's!"$BASEDIR"/conf!/etc/sds/connectors/mongodb!g' /opt/sds/connectors/mongodb/bin/stratio-connector-mongodb

case "$1" in
  configure)

  # Add stratio group if it doesn't already exists
  if ! getent group $GROUP >/dev/null 2>&1; then
    groupadd ${GROUP} 
  fi

  # Add stratio user if it doesn't already exists
  if ! getent passwd $USER >/dev/null 2>&1; then
    [ -d /opt ] || mkdir /opt
    useradd -M -d /opt/sds -g ${GROUP} -s /bin/bash ${USER}
  else
    usermod -G $GROUP $USER
  fi

  if [ ! -d "$DIR_LOG" ]; then
    mkdir $DIR_LOG
  fi

  chown root:root /etc/init.d/connector_mongodb
 
  chown -R ${USER}:${GROUP} $DIR_INSTALL
  chown -R ${USER}:${GROUP} $DIR_CONF
  chown -R ${USER}:${GROUP} $DIR_LOG
  chmod -R 775 $DIR_INSTALL
  chmod 775 $DIR_LOG
  update-rc.d connector_mongodb defaults
  ;;
esac    


exit 0

